### ISSUE TITLE
No 'save' button in text detail page

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#2]
I can't save changes to existing text because there is no 'save' button on text detail page
https://vimeo.com/544552933
1. In text list click 'edit' icon on any row
Edit Text : Modify the text page appears where text can be edited but no button to save the edits.
Expected `save` button to be present, just like on New Text page.

**Comment by gustavklopp** [comment]
Ok, it needs a bit of testing but it's working now

**Comment by m-cote** [comment]
There is a regression: I can't add new text now. Field 'id' is required in TextsForm

**Comment by gustavklopp** [comment]
I've forgotten to commit the most recent change. It's fixed now.

**Comment by m-cote** [comment]
I'm not sold on the idea of coupling My terms (some words and phrases the user learns) with My texts (something the user can read). Anyway, editing of texts worked on version 5ab8be1edda82ec7013f4b528d696f16538938fc but now I get the error in the logs every time I open the edit text page:
```
WARNING:root:Could not resolve form field 'id'.
Traceback (most recent call last):
  File "./venv/lib/python3.9/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./venv/lib/python3.9/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "./venv/lib/python3.9/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'id' not found in 'TextsForm'. Choices are: annotatedtext, archived, audiouri, language, lastopentime, owner, sourceuri, text, texttags, title."
```
and another error when 
1. edit any word
2. change the title of the text
3. click 'save'

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/text_detail/?word_edit=edited&wo_id=861

Django Version: 3.2
Python Version: 3.9.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'lwt',
 'jchart',
 'tags_input',
 'mathfilters',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "./venv/lib/python3.9/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)

During handling of the above exception ('edit'), another exception occurred:
  File "./venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "./venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./lwt/views/_nolang_redirect_decorator.py", line 15, in wrap
    return func(request, *args, **kwargs)
  File "./lwt/views/text.py", line 361, in text_detail
    text_id = request.GET['edit']
  File "./venv/lib/python3.9/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)

Exception Type: MultiValueDictKeyError at /text_detail/
Exception Value: 'edit'
```

**Comment by gustavklopp** [comment]
> I'm not sold on the idea of coupling My terms (some words and phrases the user learns) with My texts (something the user can read). 

Yes, you're right, the coupling between Words and Texts were too tight. I've changed it. Now the coupling between text and words is optional. For example, when deleting a text, you can keep your saved words. 


>Anyway, editing of texts worked on version [5ab8be1](https://github.com/gustavklopp/LingL/commit/5ab8be1edda82ec7013f4b528d696f16538938fc) but now I get the error in the logs every time I open the edit text page:

Bug fixed.
