### ISSUE TITLE
Error when importing LWT db or installing demo 

### ISSUE THREAD

**Issue by chengxicn** [gustavklopp/LingL#28]
import lwt database :

```
DeserializationError at /backuprestore/
Problem installing fixture '/Applications/LingL-0.0.0.app/Contents/MacOS/lib/media/editedOwner_ci.yaml': 
Request Method:	POST
Request URL:	http://127.0.0.1:8000/backuprestore/
Django Version:	3.2.3
Exception Type:	DeserializationError
Exception Value:	
Problem installing fixture '/Applications/LingL-0.0.0.app/Contents/MacOS/lib/media/editedOwner_ci.yaml': 
Exception Location:	/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/serializers/pyyaml.py, line 80, in Deserializer
Python Executable:	/Applications/LingL-0.0.0.app/Contents/MacOS/LingLibre
Python Version:	3.8.10
Python Path:	
['/Applications/LingL-0.0.0.app/Contents/MacOS/lib/library.zip',
 '/Applications/LingL-0.0.0.app/Contents/MacOS/lib']
Server time:	Tue, 22 Jun 2021 04:35:28 +0000


Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/backuprestore/

Django Version: 3.2.3
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'lwt',
 'tags_input',
 'mathfilters',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/serializers/pyyaml.py", line 76, in Deserializer
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    <source code not available>
  File "yaml/_yaml.pyx", line 707, in yaml._yaml.CParser.get_single_node
    <source code not available>
  File "yaml/_yaml.pyx", line 726, in yaml._yaml.CParser._compose_document
    <source code not available>
  File "yaml/_yaml.pyx", line 905, in yaml._yaml.CParser._parse_next_event
    <source code not available>

The above exception (mapping values are not allowed in this context
  in "/Applications/LingL-0.0.0.app/Contents/MacOS/lib/media/editedOwner_ci.yaml", line 6, column 1366) was the direct cause of the following exception:
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    <source code not available>
  File "/Users/lingl/lingl/LingL/lwt/views/backuprestore.py", line 173, in backuprestore
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/serializers/pyyaml.py", line 80, in Deserializer
    <source code not available>

Exception Type: DeserializationError at /backuprestore/
Exception Value: Problem installing fixture '/Applications/LingL-0.0.0.app/Contents/MacOS/lib/media/editedOwner_ci.yaml': 


```

install  LingL Demo:

```

MultipleObjectsReturned at /backuprestore/
get() returned more than one Languages -- it returned 13!
Request Method:	POST
Request URL:	http://127.0.0.1:8000/backuprestore/
Django Version:	3.2.3
Exception Type:	MultipleObjectsReturned
Exception Value:	
get() returned more than one Languages -- it returned 13!
Exception Location:	/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/db/models/query.py, line 439, in get
Python Executable:	/Applications/LingL-0.0.0.app/Contents/MacOS/LingLibre
Python Version:	3.8.10
Python Path:	
['/Applications/LingL-0.0.0.app/Contents/MacOS/lib/library.zip',
 '/Applications/LingL-0.0.0.app/Contents/MacOS/lib']
Server time:	Tue, 22 Jun 2021 04:39:16 +0000

Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/backuprestore/

Django Version: 3.2.3
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'lwt',
 'tags_input',
 'mathfilters',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    <source code not available>
  File "/Users/lingl/lingl/LingL/lwt/views/backuprestore.py", line 221, in backuprestore
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    <source code not available>
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    <source code not available>

Exception Type: MultipleObjectsReturned at /backuprestore/
Exception Value: get() returned more than one Languages -- it returned 13!

```

**Comment by gustavklopp** [comment]
can you upload here the file you're trying to import please?

**Comment by chengxicn** [comment]
[lwt-backup-2021-06-22-09-52-27.sql.gz](https://github.com/gustavklopp/LingL/files/6693148/lwt-backup-2021-06-22-09-52-27.sql.gz)

**Comment by gustavklopp** [comment]
It's working now I think: check the today release: https://github.com/gustavklopp/LingL/releases

**Comment by chengxicn** [comment]
Thank you!
It reports error when trying to login or register


```

Request Method: | GET
-- | --
http://127.0.0.1:8000/
3.2.3
ValueError
unconverted data remains:
/Users/lingl/.pyenv/versions/3.8.10/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py, line 352, in _strptime
/Applications/LingL-0.0.0.app/Contents/MacOS/LingLibre
3.8.10
['/Applications/LingL-0.0.0.app/Contents/MacOS/lib/library.zip',  '/Applications/LingL-0.0.0.app/Contents/MacOS/lib']
Wed, 23 Jun 2021 14:52:42 +0000

```





```


Traceback (most recent call last):
  File "/Users/lingl/.pyenv/versions/3.8.10/envs/venv3810/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    <source code not available>
  File "/Users/lingl/.pyenv/versions/3.8.10/envs/venv3810/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    <source code not available>
  File "/Users/lingl/.pyenv/versions/3.8.10/envs/venv3810/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    <source code not available>
  File "/Users/lingl/lingl/LingL/lwt/views/homepage.py", line 59, in homepage
    <source code not available>
  File "/Users/lingl/lingl/LingL/lwt/views/_utilities_views.py", line 47, in get_appversion
    <source code not available>
  File "/Users/lingl/.pyenv/versions/3.8.10/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    <source code not available>
  File "/Users/lingl/.pyenv/versions/3.8.10/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 352, in _strptime
    <source code not available>

Exception Type: ValueError at /
Exception Value: unconverted data remains: 

```

**Comment by gustavklopp** [comment]
Ok, I've uploaded a new version.
By the way I've added Youdao as a built-in dictionary.
(Edit your Language, and choose  the built-in 'English' language in the drop-down menu on the right. You can now choose Youdao in the drop-down menu of the dictionary link suggestion.)

![Zaslonska slika 2021-06-24 11-39-20](https://user-images.githubusercontent.com/6438275/123241248-424ced80-d4e1-11eb-839c-cc87b125990a.png)
![Zaslonska slika 2021-06-24 11-41-16](https://user-images.githubusercontent.com/6438275/123241253-4416b100-d4e1-11eb-8559-8eb616aba083.png)

**Comment by chengxicn** [comment]
WoW,thank you so much!

**Comment by Samuihasu** [comment]
Using the Docker, I also can't import LWT db

> OperationalError at /backuprestore/
Request Method: 	POST
Request URL: 	http://localhost:8000/backuprestore/
Django Version: 	3.2.4
Exception Type: 	OperationalError
Exception Value: 	disk I/O error
Exception Location: 	/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py, line 423, in execute
Python Executable: 	/root/.pyenv/versions/3.9.0/bin/python3.9
Python Version: 	3.9.0
Python Path: 	

['/app',
 '/root/.pyenv/versions/3.9.0/bin',
 '/root/.pyenv/versions/3.9.0/lib/python39.zip',
 '/root/.pyenv/versions/3.9.0/lib/python3.9',
 '/root/.pyenv/versions/3.9.0/lib/python3.9/lib-dynload',
 '/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages']

Server time: 	Sun, 01 Aug 2021 15:07:26 +0000

Environment:


Request Method: POST
Request URL: http://localhost:8000/backuprestore/

Django Version: 3.2.4
Python Version: 3.9.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'lwt',
 'tags_input',
 'mathfilters',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (disk I/O error) was the direct cause of the following exception:
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/lwt/views/backuprestore.py", line 193, in backuprestore
    files = form.save()
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /backuprestore/
Exception Value: disk I/O error
`
