### ISSUE TITLE
Fresh install, creating first text, got "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet." exception

### ISSUE THREAD

**Issue by jzohrab** [gustavklopp/LingL#44]
Issue not opened before.  Just cloned the repo today.

**Paste the Debug page**
[debug pastebin](https://pastebin.com/RjGWvAEd)

**Start of the error message**

```
RemoteError at /text_detail/
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/managers.py", line 245, in serve_client
    request = recv()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/Users/jeff/Documents/Languages/LingL/lwt/views/__init__.py", line 5, in <module>
    from lwt.views.homepage import *
  File "/Users/jeff/Documents/Languages/LingL/lwt/views/homepage.py", line 21, in <module>
    from lwt.models import *
  File "/Users/jeff/Documents/Languages/LingL/lwt/models.py", line 26, in <module>
    from django.contrib.auth.models import AbstractUser, UserManager
  File "/Users/jeff/Documents/Languages/LingL/.venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/jeff/Documents/Languages/LingL/.venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/jeff/Documents/Languages/LingL/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/jeff/Documents/Languages/LingL/.venv/lib/python3.9/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/jeff/Documents/Languages/LingL/.venv/lib/python3.9/site-packages/django/apps/registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

The app was running fine before I created my initial text.

Thank you!  I haven't moved to a new screen, I'll see if the text has somehow been processed anyway.  Cheers! jz

**Comment by jzohrab** [comment]
fyi, I went back to the homepage, and the text had indeed been imported and was ready to read.
